version: "3"
services:
  postgres:
      image: healthcheck/postgres
      #TODO Map application.sql to be executed as soon as we bring the container up
      healthcheck:
        interval: 10s
        timeout: 1s
        retries: 10
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456