version: "3"
services:
  kafka-broker:
    image: wurstmeister/kafka
    ports:
          - 9092:9092
    environment:
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://localhost:9093
      ADVERTISED_PORT: 9092
      ZOOKEEPER_IP: zookeeper
      KAFKA_CREATE_TOPICS: "inputItemTopic,errorTopic"

  zookeeper:
    image: zookeeper
    links:
          - kafka-broker
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1